export const environment = {
  clientId: 'HRM_CLIENT',
  keyCookie: 'CRM',
  production: false,
  bgLogin: '/assets/img/bg-login-crm.jpg',
  favicon: 'assets/images/crm/logo.png',
  logoIcon: '/assets/images/crm/logo.png',
  title: 'CRM',
  isPinMenu: true,
  frontend: 'https://crm2.hocviennangtam.vn/',
  backend: {
    baseUrl: 'https://crm2.hocviennangtam.vn/',
    admin: 'https://crm2.hocviennangtam.vn/admin-service',
    crm: 'https://crm2.hocviennangtam.vn/crm-service',
    library: '',
    // library: 'http://45.117.170.247:8862/library-service',
    hrm: 'https://crm2.hocviennangtam.vn/hrm-service',
    abs: '',
    // abs: 'http://45.117.170.247:8880/abs-service',
    kpi: '',
    // kpi: 'http://45.117.170.247:8879/kpi-service',
    med: '',
    // med: 'http://45.117.170.247:8873/med-service',
    lms: '',
  }
};
