export const STATUS = {
  ACTIVE: 1,
  INACTIVE: 0
};

export const CATEGORY_CODE = {
  TRANG_THAI_NV: 'HR_TRANG_THAI_NHAN_VIEN',
  TRANG_THAI_PHE_DUYET: 'TRANG_THAI_PHE_DUYET',
  TINH: 'TINH',
  HUYEN: 'HUYEN',
  XA: 'XA',
  LOAI_HINH_DON_VI: 'HR_LOAI_HINH_DON_VI',
  CAP_DON_VI_CHA: 'CAP_DON_VI_CHA',
  HINH_THUC_THANH_LAP: 'HR_HINH_THUC_THANH_LAP',
  LOAI_CHUC_DANH: 'LOAI_CHUC_DANH',
  LOAI_PHU_CAP: 'LOAI_PHU_CAP',
  GIOI_TINH: 'GIOI_TINH',
  CRM_LOAI_THANH_TOAN: 'CRM_LOAI_THANH_TOAN',
  CRM_HO_SO_NHAN_VIEN: 'CRM_HO_SO_NHAN_VIEN',
  CRM_CHUC_VU: 'CRM_CHUC_VU',
  CRM_DON_VI: 'CRM_DON_VI',
  CRM_VAI_TRO: 'CRM_VAI_TRO',
  DAN_TOC: 'DAN_TOC',
  TON_GIAO: 'TON_GIAO',
  TINH_TRANG_HON_NHAN: 'TINH_TRANG_HON_NHAN',
  LOAI_GIAY_TO: 'LOAI_GIAY_TO',
  NOI_CAP_CMT: 'NOI_CAP_CMT',
  NOI_CAP_CCCD: 'NOI_CAP_CCCD',
  MOI_QUAN_HE_TN: 'MOI_QUAN_HE_TN',
  TINH_TRANG_TN: 'TINH_TRANG_TN',
  DOI_TUONG_CHINH_SACH: 'DOI_TUONG_CHINH_SACH',
  HINH_THUC_DAO_TAO: 'HINH_THUC_DAO_TAO',
  CHUYEN_NGANH_DAO_TAO: 'CHUYEN_NGANH_DAO_TAO',
  TRUONG_DAO_TAO: 'TRUONG_DAO_TAO',
  XEP_LOAI_TN: 'XEP_LOAI_TN',
  TRINH_DO_DAO_TAO: 'TRINH_DO_DAO_TAO',
  HR_GIAI_DOAN_QUY_HOACH: 'HR_GIAI_DOAN_QUY_HOACH',
  HR_CHUC_VU_QUY_HOACH: 'HR_CHUC_VU_QUY_HOACH',
  HR_LY_DO_RA_QUY_HOACH: 'HR_LY_DO_RA_QUY_HOACH',
  HR_REPORT_TYPES: 'HR_REPORT_TYPES',
  TRINH_DO_VAN_HOA: 'TRINH_DO_VAN_HOA',
  LOAI_CHUNG_CHI: 'LOAI_CHUNG_CHI',
  TEN_CHUNG_CHI: 'TEN_CHUNG_CHI',
  NGACH_LUONG: 'NGACH_LUONG',
  BAC_LUONG: 'BAC_LUONG',
  HINH_THUC_KHEN_THUONG: 'HINH_THUC_KHEN_THUONG',
  LOAI_TO_CHUC_CTR_XH: 'LOAI_TO_CHUC_CTR_XH',
  CHUC_DANH_CTR_XH: 'CHUC_DANH_CTR_XH',
  HINH_THUC_KY_LUAT: 'HINH_THUC_KY_LUAT',
  PHAN_LOAI_HOP_DONG: 'PHAN_LOAI_HOP_DONG',
  CRM_TRANG_THAI_TGIA_HOC: 'CRM_TRANG_THAI_TGIA_HOC',
  NGAN_HANG: 'NGAN_HANG',
  LOAI_TAI_KHOAN: 'LOAI_TAI_KHOAN',
  HOC_HAM: 'HR_HOC_HAM',
  KIEU_THOI_GIAN: 'KIEU_THOI_GIAN',
  THOI_GIAN_NGHI: 'THOI_GIAN_NGHI',
  PHAN_LOAI_KPI: 'KPI_PHAN_LOAI',
  KPI_PHAN_NHOM: 'KPI_PHAN_NHOM',
  SUMMARY_TABLE_ORG: 'SUMMARY_TABLE_ORG',
  KPI_LOAI_TONG_HOP: 'KPI_LOAI_TONG_HOP',
  KPI_RESULT_TYPE: 'KPI_RESULT_TYPE',
  CHU_KY: 'KPI_CHU_KY',
  KPI_CACH_DANH_GIA: 'KPI_CACH_DANH_GIA',
  KPI_ASSIGNMENT_TYPE: 'KPI_ASSIGNMENT_TYPE',
  DON_VI_TINH: 'KPI_DON_VI_TINH',
  NAM_DANH_GIA: 'NAM_DANH_GIA',
  KY_DANH_GIA: 'KY_DANH_GIA',
  TY_LE: 'TY_LE',
  LOAI_NGACH_LUONG: 'LOAI_NGACH_LUONG',
  PHAN_LOAI_LUONG_TRUONG: 'PHAN_LOAI_LUONG_TRUONG',
  LICH_LAM_VIEC: 'LICH_LAM_VIEC',
  KPI_THANG_DO: 'KPI_THANG_DO',
  KPI_PHAN_LOAI: 'KPI_PHAN_LOAI',
  STATUS_KPI_LEVEL1: 'STATUS_KPI_LEVEL1',
  KPI_LEVEL: 'KPI_LEVEL',
  KPI_DKY_MUC_TIEU_DON_VI: 'KPI_DKY_MUC_TIEU_DON_VI',
  CHOOSE_YES_NO: 'CHOOSE_YES_NO',
  HR_TY_LE_HUONG_LUONG: 'HR_TY_LE_HUONG_LUONG',
  HR_TY_LE_LUONG_TRUONG: 'HR_TY_LE_LUONG_TRUONG',
  KPI_LOAI_DANH_GIA: 'KPI_LOAI_DANH_GIA',
  CRM_CHUNG_CHI: 'CRM_CHUNG_CHI',
  CRM_STATUS_CERTIFICATE: 'CRM_STATUS_CERTIFICATE',
  CRM_ORDER_PAYABLES_STATUS: 'CRM_ORDER_PAYABLES_STATUS',
  CRM_LOAI_DOI_TAC: 'CRM_LOAI_DOI_TAC',
  HR_TRANG_THAI_NHAN_VIEN: 'HR_TRANG_THAI_NHAN_VIEN',
  DOI_TUONG_CSKH_SN: 'DOI_TUONG_CSKH_SN',
  OBJECT_TYPE_LOG_CRM: 'OBJECT_TYPE_LOG_CRM',
  LOAI_BIEU_MAU: 'LOAI_BIEU_MAU',
  CRM_PHAN_LOAI: 'CRM_PHAN_LOAI',
  CRM_TINH_TRANG: 'CRM_TINH_TRANG',
  CRM_TRANG_THAI_CHAM_SOC: 'CRM_TRANG_THAI_CHAM_SOC',
  CRM_TRANG_THAI_SAN_PHAM: 'CRM_TRANG_THAI_SAN_PHAM',
  CRM_NHOM_SAN_PHAM: 'CRM_NHOM_SAN_PHAM',
  CRM_DVT_SAN_PHAM: 'CRM_DVT_SAN_PHAM',
  CDT_CHUYEN_MON: 'CDT_CHUYEN_MON',
  CDT_BENH_VIEN: 'CDT_BENH_VIEN',
  CDT_VAI_TRO: 'CDT_VAI_TRO',
  CDT_DIA_DIEM_DAO_TAO: 'CDT_DIA_DIEM_DAO_TAO',
  CDT_CHUONG_TRINH_DAO_TAO: 'CDT_CHUONG_TRINH_DAO_TAO',
  LMS_DOI_TUONG_NGOAI: 'LMS_DOI_TUONG_NGOAI',
  LMS_HINH_THUC_DAO_TAO: 'LMS_HINH_THUC_DAO_TAO',
  LMS_CHUYEN_NGANH_NGOAI_VIEN: 'LMS_CHUYEN_NGANH_NGOAI_VIEN',
  LMS_TINH_TRANG_HOC_PHI: 'LMS_TINH_TRANG_HOC_PHI',
  NCKH_PHAN_LOAI_DE_TAI: 'NCKH_PHAN_LOAI_DE_TAI',
  NCKH_CAP_NGHIEN_CUU: 'NCKH_CAP_NGHIEN_CUU',
  NCKH_HE_NGHIEN_CUU: 'NCKH_HE_NGHIEN_CUU',
  NCKH_TRANG_THAI: 'NCKH_TRANG_THAI',
  NCKH_VAI_TRO: 'NCKH_VAI_TRO',
  CRM_TRANG_THAI_KHACH_HANG: 'CRM_TRANG_THAI_KHACH_HANG',
  LMS_INTERN_TRUONG_DAO_TAO: 'LMS_INTERN_TRUONG_DAO_TAO',
  LMS_INTERN_CHUYEN_NGANH: 'LMS_INTERN_CHUYEN_NGANH',
  LMS_NOI_DUNG_DAO_TAO: 'LMS_NOI_DUNG_DAO_TAO',
  LMS_NOI_DAO_TAO: 'LMS_NOI_DAO_TAO',
  LMS_KE_HOACH_DAO_TAO: 'LMS_KE_HOACH_DAO_TAO',
  LMS_KHOA_DAO_TAO: 'LMS_KHOA_DAO_TAO',
  LMS_NGUON_KINH_PHI: 'LMS_NGUON_KINH_PHI',
  ABS_LOAI_DK_LAM_THEM: 'ABS_LOAI_DK_LAM_THEM',
  ABS_LY_DO_DC_CHAM_CONG: 'ABS_LY_DO_DC_CHAM_CONG',
  KPI_REPORT: 'KPI_REPORT',
  HRM_DOT_KHAM_SUC_KHOE: 'HRM_DOT_KHAM_SUC_KHOE',
  HRM_XEP_LOAI_SUC_KHOE: 'HRM_XEP_LOAI_SUC_KHOE',
  HRM_BENH_GAP_PHAI: 'HRM_BENH_GAP_PHAI',
  SYS_LOAI_BIEU_DO: 'SYS_LOAI_BIEU_DO',
  KPI_TEMPLATES_TYPE: 'KPI_TEMPLATES_TYPE',
  SYS_TRANG_THAI_PHAN_ANH: 'SYS_TRANG_THAI_PHAN_ANH',
  EQUIPMENT_UNIT: 'EQUIPMENT_UNIT',
  EQUIPMENT_TYPE: 'EQUIPMENT_TYPE',
  EQUIPMENT_GROUP: 'EQUIPMENT_GROUP',
  WAREHOUSE_TYPE: 'WAREHOUSE_TYPE',
  ACTIVE_STATUS: 'ACTIVE_STATUS',
  KHOAN_THU_NHAP: 'KHOAN_THU_NHAP',
  THU_NHAP_DA_TINH_THUE: 'THU_NHAP_DA_TINH_THUE',
  TAX_DECLARE_MASTERS_STATUS: 'TAX_DECLARE_MASTERS_STATUS',
  PIT_TRANG_THAI_TNCN: 'PIT_TRANG_THAI_TNCN',
  THUE_LOAI_THU_NHAP: 'THUE_LOAI_THU_NHAP',
  INCOME_ITEM_STATUS: 'INCOME_ITEM_STATUS',
  INCOME_REPORT_TYPE: 'INCOME_REPORT_TYPE',
  LOAI_DS_TRICH_NOP: 'LOAI_DS_TRICH_NOP',
  LOAI_THAY_DOI: 'LOAI_THAY_DOI',
  TRANG_THAI_TRICH_NOP: 'TRANG_THAI_TRICH_NOP',
  TRANG_THAI_RA_SOAT_DU_LIEU: 'TRANG_THAI_RA_SOAT_DU_LIEU',
  ICN_LOAI_BAO_CAO: 'ICN_LOAI_BAO_CAO',
  NOI_TGIA_BHXH: 'NOI_TGIA_BHXH',
  TRANG_THAI_THU_BHXH: 'TRANG_THAI_THU_BHXH',
  ICN_LOAI_DS_TRICH_NOP: 'ICN_LOAI_DS_TRICH_NOP',
  ICN_TRANG_THAI_THU_BHXH: 'ICN_TRANG_THAI_THU_BHXH',
  LOAI_PHAN_ANH: 'LOAI_PHAN_ANH',
  MAT_INCOMING_SHIPMENTS_TYPE: 'MAT_INCOMING_SHIPMENTS_TYPE',
  MAT_STATUS: 'MAT_STATUS',
  MAT_INVENTORY_ADJUSTMENT_TYPE: 'MAT_INVENTORY_ADJUSTMENT_TYPE',
  MAT_OUTGOING_SHIPMENT_TYPE: 'MAT_OUTGOING_SHIPMENT_TYPE',
  HRM_LOG_TASK: 'HRM_LOG_TASK',
  MAT_REPORT_TYPE: 'MAT_REPORT_TYPE',
  EXAM_SUBJECT: 'EXAM_SUBJECT',
  EXAM_TOPIC: 'EXAM_TOPIC',
  EXAM_TYPE: 'EXAM_TYPE',
  EXAM_MODE: 'EXAM_MODE',
  EXAM_SEMESTER: 'EXAM_SEMESTER',
  EXAM_SESSIONS_STATUS: 'EXAM_SESSIONS_STATUS'
};

export class Constant {

  public static readonly OTHER_VALUE = '-1';
  public static readonly STATUS = {
    INIT: 1,
    WAIT_APPROVE: 2,
    APPROVED: 3,
    REJECT: 4
  };
  public static readonly STATUSES_EMPLOYEE = [
    { label: 'personalTax.label.workIn', value: '1' },
    { label: 'personalTax.label.contractPending', value: '2' },
    { label: 'personalTax.label.workOut', value: '3' }
  ];
  public static readonly CATALOGS = {
    GIOI_TINH: 'GIOI_TINH',
    DAN_TOC: 'DAN_TOC',
    TON_GIAO: 'TON_GIAO',
    TINH_TRANG_HON_NHAN: 'TINH_TRANG_HON_NHAN',
    TINH: 'TINH',
    HUYEN: 'HUYEN',
    XA: 'XA',
    LOAI_TAI_KHOAN: 'LOAI_TAI_KHOAN',
    LOAI_GIAY_TO: 'LOAI_GIAY_TO',
    MA_VUNG_DIEN_THOAI: 'MA_VUNG_DIEN_THOAI',
    QUOC_GIA: 'QUOC_GIA',
    DOI_TUONG_CV: 'DOI_TUONG_CV',
    CAP_BAC_QUAN_HAM: 'CAP_BAC_QUAN_HAM',
    LEVEL_NV: 'LEVEL_NV',
    PHAN_LOAI_HOP_DONG: 'PHAN_LOAI_HOP_DONG',
    LOAI_HINH_DT: 'LOAI_HINH_DT',
    LOAI_BANG_CAP: 'LOAI_BANG_CAP',
    HE_DT: 'HE_DT',
    HINHTHUC_DAOTAO: 'HINHTHUC_DAOTAO',
    XEP_LOAI_DT: 'XEP_LOAI_DT',
    XEP_LOAI_TOT_NGHIEP: 'XEP_LOAI_TOT_NGHIEP',
    MOI_QUAN_HE_NT: 'MOI_QUAN_HE_NT',
    TINH_TRANG_NT: 'TINH_TRANG_NT',
    DOITUONG_CHINHSACH: 'DOITUONG_CHINHSACH',
    CAP_QD_KHENTHUONG: 'CAP_QD_KHENTHUONG',
    HINHTHUC_KHENTHUONG: 'HINHTHUC_KHENTHUONG',
    LOAI_KHENTHUONG: 'LOAI_KHENTHUONG',
    HINHTHUC_KYLUAT: 'HINHTHUC_KYLUAT',
    LOAI_HO_SO: 'LOAI_HO_SO',
    LOAI_PHU_CAP: 'LOAI_PHU_CAP',
    CAP_QD_KYLUAT: 'CAP_QD_KYLUAT'
  };
  public static readonly EXCEL_TYPE_1 = 'xls';
  public static readonly EXCEL_MIME_1 = 'application/vnd.ms-excel';
  public static readonly EXCEL_TYPE_2 = 'xlsx';
  public static readonly EXCEL_MIME_2 = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
  public static readonly PDF_TYPE = 'pdf';
  public static readonly PDF_MIME = 'application/pdf';
}

export class ConstantColor {
  public static readonly COLOR = {
    BG_PRIMARY_DARK: '#24264E',
    BG_PRIMARY_DARKER: '#00009A',
    BG_PRIMARY_DEFAULT: '#141ED2',
    BG_PRIMARY_LIGHT: '#7F85F3',
    BG_PRIMARY_BG: '#E9EAFF',
    DISABLED: '#c0c0c0'
  };
  public static readonly TAG = {
    STATUS_INITIALIZE: '#E8EAF6', // Khởi tạo
    STATUS_APPROVED: '#DAF9EC', // Phê duyệt
    STATUS_NOT_APPROVED: '#FFC9C9',  // Từ chối
    STATUS_IS_WORKING: '#DAF9EC', // Hiện diện
    STATUS_SUSPENSE: '#FFF2DA', // Tạm hoãn
    STATUS_RETIRED: '#FDE7EA' // Đã nghỉ việc
  };
}

export enum Mode {
  ADD,
  EDIT,
  VIEW
}

export enum REQUEST_TYPE {
  DEFAULT,
  FORM_DATA,
  FORM_DATA_FILE,
}

export const TABLE_CONFIG_DEFAULT = {
  pageSize: 20
};

export class FileConstant {
  // EXCEL
  public static readonly EXCEL_TYPE_1 = 'xls';
  public static readonly EXCEL_MIME_1 = 'application/vnd.ms-excel';
  public static readonly EXCEL_TYPE_2 = 'xlsx';
  public static readonly EXCEL_MIME_2 = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
// PDF
  public static readonly PDF_TYPE = 'pdf';
  public static readonly PDF_MIME = 'application/pdf';
  // WORD
  public static readonly DOC_TYPE = 'doc';
  public static readonly DOC_MIME = 'application/msword';
  public static readonly DOCX_TYPE = 'docx';
  public static readonly DOCX_MIME = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
}
